### ISSUE TITLE
Crash after updating from 2.1.0 to 2.1.1

### ISSUE THREAD

**Issue by morganlutz** [castle/castle-android#47]
Hi all,

We recently attempted to update from 2.1.0 to 2.1.1. Updating castle to this version caused a crash on launch of our app. Potentially it's something related to highwind which also got a transitive update from castle?

The crash cause:
```
356  1417  1417 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lio/castle/android/geozip/Location;
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.highwind.Highwind.token(Unknown Source:7)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.Castle.id(Castle.java:96)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.Castle.createRequestToken(Castle.java:306)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.api.model.Context.init(Context.java:25)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.api.model.Context.create(Context.java:30)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.Castle.createContext(Castle.java:462)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.api.model.Event.<init>(Event.java:41)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.Castle.track(Castle.java:168)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.Castle.registerLifeCycleCallbacks(Castle.java:82)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at io.castle.android.Castle.configure(Castle.java:135)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at com.trello.app.TrelloApplication.initializeCastle(TrelloApplication.kt:349)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at com.trello.app.TrelloApplication.initialize(TrelloApplication.kt:140)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at com.trello.app.TrelloApplication.onCreate(TrelloApplication.kt:75)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
09-01 11:19:36.356  1417  1417 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
and:
```
AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "io.castle.android.geozip.Location" on path: DexPathList
```

Using Android Studio Arctic Fox 2020.3.1 & Gradle 7.0.2

**Comment by sebastiansimson** [comment]
Thank you for reporting this, the proguard rules have now been corrected and this is solved in release 2.1.2
